### PR TITLE
fixed breakpoints display problem when using cgdb.

### PR DESCRIPTION
**Pull request by iscooool**
I'm using cgdb currently. But some layouts like breakpoints and sources are not displayed correctly. I found out that when `run('info breakpoints')`, the return strings' format in cgdb is different from gdb's. I try to fix this problem by converting it to gdb's format. if fails, the function will fall back to original gdb's format, which indicates that gdb (not cgdb) is running.
Although this project is disigned for gdb not for cgdb, is it any chances to accept this pull request? Any decisions will be OK.

### CODE REVIEW

**Comment by cyrus-and** [comment]
How can you use CGDB with the dashboard? Basically nothing works out-of-the-box...

Anyway, in my brief tests the output of `info breakpoints` does not change between GDB and CGDB, how can I reproduce that?

In any case I won't merge this because supporting CGDB (or any other frontends) is not planned. What you can do instead is *monkey-patch* `fetch_breakpoints` or `run` by placing a `.py` file in your `~/.gdbinit.d/` folder, for example:

```py
def run(command):
    output = gdb.execute(command, to_string=True)
    if command == 'info breakpoints':
        output = convert_breakpoints_cgdb(output)
    return output
```

**Comment by iscooool** [comment]
That's weird. I'm using CGDB v0.7.1 and running it on WSL. It works properly.
image
When I delete `convert_breakpoints_cgdb` and write `run('info breakpoints')`'s return value to `log.txt`, something like the left bottom side of screenshot has been written.
image

**Comment by cyrus-and** [comment]
What's the output of `info breakpoints` in CGDB without the dashboard?

**Comment by cyrus-and** [comment]
And what about GDB with the dashboard (no CGDB), everything works properly?

**Comment by iscooool** [comment]
It works properly.
image

**Comment by cyrus-and** [comment]
I compiled the latest CGDB version and still can't reproduce it. The weird output you get appears in the output of the MI interface (spurious `~` lines):

```
>>> interpreter-exec mi -break-list
~"\n\032\032breakpoints-table-end\n"
^done,BreakpointTable={nr_rows="0",nr_cols="6",hdr=[{width="7",alignment="-1",col_name="number",colhdr="Num"},{width="14",alignment="-1",col_name="type",colhdr="Type"},{width="4",alignment="-1",col_name="disp",co
lhdr="Disp"},{width="3",alignment="-1",col_name="enabled",colhdr="Enb"},{width="10",alignment="-1",col_name="addr",colhdr="Address"},{width="40",alignment="2",col_name="what",colhdr="What"}],body=[]}            
```

I have no idea why you're seeing this, in any case you can always fix it as I told you [before][1].

What's the point of using the dashboard inside CGDB though?

[1]: https://github.com/cyrus-and/gdb-dashboard/pull/170#issuecomment-546910021

**Comment by iscooool** [comment]
I just like the feature of redirect different layouts to different ttys.
Anyway, thanks for your reply!

**Comment by cyrus-and** [comment]
> I just like the feature of redirect different layouts to different ttys.

I mean why not simply using vanilla GDB with the dashboard?

**Comment by iscooool** [comment]
I'm quite new to GDB actually. I like vim–like key bindings and search feature in CGDB and some features of gdb–dashboard. So I try to combine them. It's a personal taste issue. Maybe there is a better way to do this and I just don't know how to do.

**Comment by cyrus-and** [comment]
I see, thanks for the explanation. I'm closing this now. Feel free to comment though if you have any question.

**Pull request closed without merging**
