### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by borgmanJeremy**
Added directions for setting locale in docker container. This resolve a Unicode error in python.

### CODE REVIEW

**Comment by cyrus-and** [comment]
It's not strictly the fact that GDB is running in a Docker container the problem, it actually depends on *what* Docker container, and it's not a much different scenario with respect to a poorly configured environment.

In fact the following works as expected:

```console
$ docker run --rm -it --privileged ubuntu:16.04
root@bf7115f652db:/# apt update && apt install -y wget gdb
root@bf7115f652db:/# wget -P ~ git.io/.gdbinit
root@bf7115f652db:/# gdb -ex 'b __libc_start_main' -ex r ls
```

**Comment by borgmanJeremy** [comment]
The issue I had was when I tried to redirect the output to another terminal within docker I got a unicode error similar to this issue https://github.com/cyrus-and/gdb-dashboard/issues/61

GDB worked overall but could not properly redirect the output. Maybe it's worth adding a Requirements section or something to the readme to document stuff like this?

**Comment by cyrus-and** [comment]
> Maybe it's worth adding a Requirements section or something to the readme to document stuff like this?

The problem is that I'm not sure (I'm pretty sure of the opposite actually) that exporting that env var is the proper solution. Let me look into it.

**Comment by cyrus-and** [comment]
Well, I guess the notice is enough for now...

Reworded and changed place.

**Comment by borgmanJeremy** [comment]
Great thanks

**Pull request closed without merging**
