### PR TITLE
Add an option to dereference local pointers

### PR DESCRIPTION
**Pull request by gavinhoward**
This covers a case that I want, where I can dereference local pointers without having to type

```
p *<local_pointer_name>
```

It is implemented as a style option, and its default is `False` to not break existing users' workflows.

### CODE REVIEW

**Comment by cyrus-and** [comment]
While I understand the problem this PR is trying to solve, I find the solution both confusing (there is no way to distinguish a pointer from the actual value) and too specialized (what about pointer to pointer etc.?).

This could be the chance to implement something I've been thinking for a while now, that is an additional annotation to any pointer that shows the value that is *eventually* pointed. Something like:

```
loc x = 123
loc px = 0x7fffffffe61c: 123
loc ppx = 0x7fffffffe610: 123
loc pppx = 0x7fffffffe608: 123
loc ppppx = 0x7fffffffe600: 123
loc pppppx = 0x7fffffffe5f8: 123
```

**Comment by gavinhoward** [comment]
Hmm...I think I can do that.

**Comment by cyrus-and** [comment]
No, I mean (sorry for the misleading message) it's already done: 4dba9f18aa3acba62a96018c7ab0b559df73004a

**Comment by gavinhoward** [comment]
Works for me. Thank you very much.

**Pull request closed without merging**
