### PR TITLE
[WIP] add Neovim detection and support

### PR DESCRIPTION
**Pull request by P4Cu**
This is a [WorkInProgress] pull request.

Hi,
I've wrote a small sample how Neovim could be easily integrated into the script.
For now it only opens a source view when it detects that it runs inside of nvim. Then it follows the current line (also adding a mark => ).
How about adding such feature?

I would plan to do a few more things like breakpoints etc.

### CODE REVIEW

**Comment by cyrus-and** [comment]
Well, I just peeked into the code but it seems to me quite a lot of changes for just an editor integration. By the way I don't really feel like to add editor-specific code to the dashboard, that's not the proper place IMHO.

Nevertheless I understand that this could be a nice feature for Neovim users. Can this be implemented as an auxiliary [Python init file][1] or maybe (unlikely) a custom module? 

With a bit of *Python-fu* it should be possible to override several aspects of the dashboard in that way; it may be worth to give it a try.

[1]: https://github.com/cyrus-and/gdb-dashboard#configuration

**Comment by P4Cu** [comment]
Well that have been done as an additional module but the 'diff' does not pick it correctly and detects it as a total change. What I have done is just guarding the module definition with a **if Dashboard.nvim() is None:** and adding Nvim module ;-)
Although the idea of doing it as a Python init file is quite fine but I'm                                                                                        more and more convinced that it may turn out that having it independently with just picking some parts of the code (of course keeping you in credit of that work ;-) ). BTW nice design idea.

**Comment by P4Cu** [comment]
Well that can be done via module file which is fine for me ;-)

**Comment by cyrus-and** [comment]
That's great!

**Pull request closed without merging**
